#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC36CDCB4DF00C68C (infra-root@openstack.org)
#
Name     : futurist
Version  : 1.7.0
Release  : 37
URL      : https://tarballs.openstack.org/futurist/futurist-1.7.0.tar.gz
Source0  : https://tarballs.openstack.org/futurist/futurist-1.7.0.tar.gz
Source99 : https://tarballs.openstack.org/futurist/futurist-1.7.0.tar.gz.asc
Summary  : Useful additions to futures, from the future.
Group    : Development/Tools
License  : Apache-2.0
Requires: futurist-python3
Requires: futurist-license
Requires: futurist-python
Requires: contextlib2
Requires: futures
Requires: monotonic
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python3-dev
BuildRequires : setuptools

%description
Team and repository tags
        ========================

%package license
Summary: license components for the futurist package.
Group: Default

%description license
license components for the futurist package.


%package python
Summary: python components for the futurist package.
Group: Default
Requires: futurist-python3

%description python
python components for the futurist package.


%package python3
Summary: python3 components for the futurist package.
Group: Default
Requires: python3-core

%description python3
python3 components for the futurist package.


%prep
%setup -q -n futurist-1.7.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532380428
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/futurist
cp LICENSE %{buildroot}/usr/share/doc/futurist/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/futurist/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
