#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xC12B8E73B30F2FC8 (infra-root@openstack.org)
#
Name     : futurist
Version  : 2.2.0
Release  : 45
URL      : https://tarballs.openstack.org/futurist/futurist-2.2.0.tar.gz
Source0  : https://tarballs.openstack.org/futurist/futurist-2.2.0.tar.gz
Source1  : https://tarballs.openstack.org/futurist/futurist-2.2.0.tar.gz.asc
Summary  : Useful additions to futures, from the future.
Group    : Development/Tools
License  : Apache-2.0
Requires: futurist-license = %{version}-%{release}
Requires: futurist-python = %{version}-%{release}
Requires: futurist-python3 = %{version}-%{release}
Requires: pbr
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : pbr
BuildRequires : six

%description
Team and repository tags
        ========================

%package license
Summary: license components for the futurist package.
Group: Default

%description license
license components for the futurist package.


%package python
Summary: python components for the futurist package.
Group: Default
Requires: futurist-python3 = %{version}-%{release}

%description python
python components for the futurist package.


%package python3
Summary: python3 components for the futurist package.
Group: Default
Requires: python3-core
Provides: pypi(futurist)
Requires: pypi(pbr)
Requires: pypi(six)

%description python3
python3 components for the futurist package.


%prep
%setup -q -n futurist-2.2.0
cd %{_builddir}/futurist-2.2.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1594660955
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/futurist
cp %{_builddir}/futurist-2.2.0/LICENSE %{buildroot}/usr/share/package-licenses/futurist/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/futurist/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
